### PR TITLE
Glariamn politics socdem ccfox

### PR DESCRIPTION
**Pull request by ghost**
Here's the current socdem branch. Feel free to adapt it to any upcoming changes.

### CODE REVIEW

**Comment by ccfox** [comment]
Thanks, adding social democracy as an ideology is what I'm going to be working on next after merging the dynamic branch changes. I'll likely make a branch - since many many several hundreds of edits are going to have to be made (and also a few events are still broken).

**Comment by ghost** [comment]
@ccfox stop, I got this.

**Comment by ccfox** [comment]
Okay.

**Comment by ghost** [comment]
@ccfox should I close this?

**Comment by ccfox** [comment]
Not yet, I have my fork bookmarked so its easier to get to your branch by clicking that and then clicking on the pull request.

**Comment by ghost** [comment]
@ccfox The ideology name in your fork's governments.txt and ideologies.txt is wrong.

**Comment by ccfox** [comment]
Thanks, fixed it.

**Comment by ghost** [comment]
This branch needs to be checked for silent deletions and additions caused by merge conflict resolution, but it's finished

**Pull request merged**
