### PR TITLE
Tech and invention changes 2nd attempt

### PR DESCRIPTION
**Pull request by ghost**
-Removed and replaced anachronistic inventions copied from Vic2
-Only naval_bases_tech increases maximum naval base level
-supply_range is increased by naval_bases_tech instead of ship_systems
-Naval rocket techs are moved into ship_systems
-added new naval inventions
-Added level three naval_base techs to some countries
-More late-game spacecraft techs. Currently fluff only.
-Removed carrier_battle_groups from some countries
-Added and removed third_generation_jet_fighters from some countries
I had added some fixes for the space race but something at the back of my mind says I should check if somebody else made those changes already.
Changed three culture techs

New tech pictures, and old pictures from early CWE, including missile_guidance_system, power_projection, helicopter_carrier (was sea_control_ships.tga)

bugfix

bugfix

update and bugfix

fix

fix

fix

Reorganized inventions

### CODE REVIEW

**Comment by ghost** [comment]
@ccfox is there anything wrong with the idea?

**Comment by ccfox** [comment]
No, but its a lot to go through, and I'm not sure what all the changes actually are.

What is doc/test for? What are the map changes?

Also, I haven't made my own repository yet, but I made a test one to put up all the changes I plan to make:
https://github.com/ccfox/CWE-FoxFork/issues/1

**Comment by ghost** [comment]
@ccfox I saw some obsolete and nonfunctional code in doc/test when replacing the techs and decided to update it to the latest tech system.

The map change should just be the Lesser Antilles bugfix; why Github displays it after merging master into tech2 I don't know.

**Comment by ghost** [comment]
@ccfox there, the commit histories are harmonized. No more map changes and unrelated stuff.

**Comment by ccfox** [comment]
Sorry, I've been busy. I am also experiencing issues with crashes (not with this, with the culture rework branch) - trying to figure out what happened to cause them.

**Pull request merged**
