### PR TITLE
Merged Dynamic and upstream commits into master

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@ccfox ?

**Comment by ccfox** [comment]
What?

**Comment by ghost** [comment]
This PR should fix a few bugs left in this fork, but I don't know if you want to stop development of old CWE repo.

**Comment by ccfox** [comment]
I don't have the time to maintain it if I'm going to be focusing on a wholly different fork. So if any bugs arise, I wouldn't be able to fix them, or alter them with any consistency. And I can already see a few things that would cause launch issues.

**Comment by ghost** [comment]
@ccfox which things will cause launch problems?

**Comment by ccfox** [comment]
The biggest is adding in reformist as an ideology without editing the ideologies file.

**Comment by ghost** [comment]
I double checked the ideology file and reformist is there. Are there any other issues?

https://github.com/Outta-my-way-burrocrat/Victoria-2-Cold-War-Enhancement-Mod-CWE/blob/c7373aeda70bf91e04af98f7882273531303b810/CWE/common/ideologies.txt#L79

**Comment by ccfox** [comment]
I am not seeing it. I also still can't maintain two completely separate versions of the mod.

Especially when I'm still actively trying to add things to the other and solve issues that CWE itself had.

**Comment by ghost** [comment]
Understood.

**Pull request closed without merging**
