### PR TITLE
Adapted commonwealth british-english pops from arandomperson5000 and nwomod

### PR DESCRIPTION
**Pull request by ghost**
Pops are divided between home island british and multicultural commonwealth english
Renamed english culture to reduce confusion
https://github.com/simsulla/nwomod

### CODE REVIEW

**Comment by ghost** [comment]
@ccfox I'm probably going to continue fixing some bugs but I don't intend to take the mantle of CWE vic2 developer; would you like to look at the remaining tweak branches in my repo? Programming language is a discoveries tech: https://github.com/Outta-my-way-burrocrat/Victoria-2-Cold-War-Enhancement-Mod-CWE/tree/tech 
Unmerged party tweaks, bugfixes and other stuff https://github.com/Outta-my-way-burrocrat/Victoria-2-Cold-War-Enhancement-Mod-CWE/tree/private_fork3
A hybrid of the old tech tree and the new+issues changes https://github.com/Outta-my-way-burrocrat/Victoria-2-Cold-War-Enhancement-Mod-CWE/tree/private_fork4

**Comment by ccfox** [comment]
Sure, though right now what I'm trying to do is clean up those essential event files, so since these alter those it might have to wait. A lot of them need to be fixed so that it is easier to port them over to CWE3 (and also because some of those events are as old as nwo and haven't been touched since).


If you are removing the British culture (which acts as a representation of people that are not English, Scottish, Welsh, or Irish - but instead either some combination or the four or diaspora), then I'd keep it as just being named English.


As for the others, I'd have to know exactly what is changed.

**Comment by ghost** [comment]
>If you are removing the British culture (which acts as a representation of people that are not English, Scottish, Welsh, or Irish - but instead either some combination or the four or diaspora), then I'd keep it as just being named English.

@settintotrieste @ccfox I'm not removing the British culture, the english/Anglophone culture is intended to represent that now. Whether a pop is British or Anglophone will represent their support for direct rule from London and racial Britishness or liberal and cosmopolitan Britishness. The present PR is very rough and only intended as a placeholder.

**Comment by ccfox** [comment]
Alright, I see!

**Comment by ghost** [comment]
@ccfox closing this and moving it to branch [anglophone](https://github.com/Outta-my-way-burrocrat/Victoria-2-Cold-War-Enhancement-Mod-CWE/tree/anglophone). Have you stopped work on branch dynamic?

**Comment by ccfox** [comment]
Sorry for not replying. I've been busy, and will likely continue to be fairly busy for a while. The dynamic branch was meant to have changes regarding cleaning up the event organization (and removing duplicate, depreciated, or broken events) as well as to alter some of the more recent stuff so that events have a greater variation in their outcomes. The hope was it would make later changes a lot easier - as a few people are still slowly working on stuff, but much slower.

**Pull request closed without merging**
